import type { Linter } from 'eslint';

import { obsidianDevUtilsConfigs } from 'obsidian-dev-utils/ScriptUtils/ESLint/eslint.config';

const configs: Linter.Config[] = [
  ...obsidianDevUtilsConfigs,
  {
    ignores: ['**/*.test.ts', '**/*.test.tsx', '**/__tests__/**', '**/__mocks__/**']
  },
  {
    rules: {
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-deprecated': 'off',
      '@typescript-eslint/explicit-member-accessibility': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      'no-alert': 'off',
      'no-void': 'off',
      'no-empty': 'off',
      'no-misleading-character-class': 'off',
      'prefer-template': 'off',
      '@typescript-eslint/dot-notation': 'off',
      '@typescript-eslint/prefer-regexp-exec': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      '@typescript-eslint/await-thenable': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      'capitalized-comments': 'off',
      'curly': 'off',
      '@typescript-eslint/array-type': 'off',
      'perfectionist/sort-classes': 'off',
      'perfectionist/sort-interfaces': 'off',
      'perfectionist/sort-object-types': 'off',
      'perfectionist/sort-union-types': 'off',
      'perfectionist/sort-modules': 'off',
      'perfectionist/sort-objects': 'off',
      'perfectionist/sort-named-imports': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-intersection-types': 'off',
      'perfectionist/sort-sets': 'off',
      'modules-newlines/import-declaration-newline': 'off',
      '@stylistic/object-curly-newline': 'off',
      '@stylistic/no-multi-spaces': 'off',
      '@stylistic/operator-linebreak': 'off',
      '@stylistic/quotes': 'off',
      '@stylistic/quote-props': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      'no-bitwise': 'off',
      'no-lonely-if': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off'
    }
  },
  {
    rules: {
      // Pragmatic overrides for beta release — these rules are extremely noisy
      // and don't affect runtime safety. They will be re-enabled incrementally
      // after the public beta stabilizes.
      'no-magic-numbers': 'off',
      '@stylistic/max-statements-per-line': 'off',
      'no-control-regex': 'off',
      'no-useless-escape': 'off',
      'prefer-named-capture-group': 'off',
      'no-nested-ternary': 'off',
      'no-negated-condition': 'off',
      'func-style': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/no-invalid-void-type': 'off',
      'no-console': 'off',
      'camelcase': 'off',
      'complexity': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      'import-x/no-nodejs-modules': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-conversion': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/no-base-to-string': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-deprecated': 'off',
      '@typescript-eslint/explicit-member-accessibility': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      'no-alert': 'off',
      'no-void': 'off',
      'no-empty': 'off',
      'no-misleading-character-class': 'off',
      'prefer-template': 'off',
      '@typescript-eslint/dot-notation': 'off',
      '@typescript-eslint/prefer-regexp-exec': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      '@typescript-eslint/await-thenable': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      'capitalized-comments': 'off',
      'curly': 'off',
      '@typescript-eslint/array-type': 'off',
      'perfectionist/sort-classes': 'off',
      'perfectionist/sort-interfaces': 'off',
      'perfectionist/sort-object-types': 'off',
      'perfectionist/sort-union-types': 'off',
      'perfectionist/sort-modules': 'off',
      'perfectionist/sort-objects': 'off',
      'perfectionist/sort-named-imports': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-intersection-types': 'off',
      'perfectionist/sort-sets': 'off',
      'modules-newlines/import-declaration-newline': 'off',
      '@stylistic/object-curly-newline': 'off',
      '@stylistic/no-multi-spaces': 'off',
      '@stylistic/operator-linebreak': 'off',
      '@stylistic/quotes': 'off',
      '@stylistic/quote-props': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      'no-bitwise': 'off',
      'no-lonely-if': 'off'
    }
  }
];

// eslint-disable-next-line import-x/no-default-export -- ESLint infrastructure requires a default export.
export default configs;
